// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conf} from '../models';

export function ChoseDir():Promise<string>;

export function GetConf():Promise<conf.Conf>;

export function Greet(arg1:string):Promise<string>;
