// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoseDir() {
  return window['go']['main']['App']['ChoseDir']();
}

export function GetConf() {
  return window['go']['main']['App']['GetConf']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
